# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
  routing_loader:
    default_format: json
  param_fetcher_listener:  true
  format_listener:
    rules:
      - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
      - { path: '^/', stop: true }
      - { path: '^/admin', stop: true }
  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  exception:
    enabled: false
  view:
    mime_types:
      json: ['application/json']
    formats: { json: true, xml: false, rss: false }
    view_response_listener: true
  serializer:
    serialize_null: true


