App\Entity\User:
    constraints:
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [username, client]
          errorPath: usernane
          message: 'The username "{{ value }}" is already in use on this compagny.'
      - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
          fields: [email, client]
          errorPath: email
          message: 'The email  "{{ value }}" is already in use on this compagny.'
    properties:
        username:
            - NotBlank: ~
            - Length:
                min: 3
                max: 100
                minMessage: 'The Username "{{ value }}" must be more than 3 characters'
                maxMessage: 'The Username "{{ value }}" can not be more than 100 characters'
        email:
            - Email:
                  message: 'The email "{{ value }}" is not a valid email.'
            - NotBlank: ~
            - Length:
                  min: 6
                  max: 255
                  minMessage: 'The Email "{{ value }}" must be more than 6 characters'
                  maxMessage: 'The Email "{{ value }}" can not be more than 100 characters'
        createdAt:
          - DateTime: ~